const LowerBodyHardExercises = [
  "Pistol Squats (Single Leg Squats)",
  "Jumping Lunges",
  "Bulgarian Split Squats with Raised Rear Foot",
  "Sissy Squats",
  "Single-Leg Box Squats",
  "Split Squats",
  "Reverse Lunges with Knee Drive",
  "Cossack Squats",
  "Frog Jumps",
  "Plyometric Lunges",
  "Depth Jumps",
  "Single-Leg Squats to Bench",
  "Box Jumps",
  "Jump Squats with Hold",
  "Lateral Lunge Jumps",
  "Single-Leg Romanian Deadlifts",
  "Jumping Squats",
  "Explosive Step-Ups",
  "Single-Leg Box Jumps",
  "Pulsing Squats",
  "Skater Lunges",
  "Curtsy Lunges",
  "Jumping Curtsy Lunges",
  "Squat Jumps with Calf Raise",
  "Alternating Jump Lunges",
  "Squat Pulses",
  "Lunge Pulses",
  "Jumping Bulgarian Split Squats",
  "Jumping Cossack Squats",
];

export default LowerBodyHardExercises;
