const CoreHardExercises = [
  "Dragon Flags",
  "Hanging Leg Raises",
  "Plank with Knee Tucks",
  "Hollow Body Hold with Flutter Kicks",
  "Ab Wheel Rollouts",
  "L-sit Holds",
  "Russian Twist with Weight",
  "Medicine Ball Slams",
  "Tuck Ups",
  "Single-Leg V-Ups",
  "Plank with Alternating Leg and Arm Lifts",
  "Slider Pike Tucks",
  "Hanging Windshield Wipers",
  "Spiderman Planks",
  "Turkish Get-Ups",
  "Standing Cable Wood Chops",
  "Decline Russian Twists",
  "Stability Ball Rollouts",
  "Leg Raises with Hip Thrust",
  "Commando Planks",
  "Reverse Plank",
  "Hanging Bicycle Crunches",
  "Body Saws",
  "Hollow Body Hold with Scissor Kicks",
  "Plank with Side Knee Raises",
  "Side Plank with Hip Dips and Reach",
  "Pike Push-Ups",
  "Handstand Holds",
  "Windmill Planks",
  "Spiderman Crawl",
];

export default CoreHardExercises;
