const UpperBodyHardExercises = [
  "One-arm push-ups",
  "Archer push-ups",
  "Typewriter push-ups",
  "Clapping push-ups",
  "Spiderman push-ups",
  "Hindu push-ups",
  "Pike push-ups",
  "Handstand push-ups",
  "Wall walks",
  "Dive bomber push-ups",
  "Explosive push-ups",
  "Tiger bend push-ups",
  "Planche push-ups",
  "Superman push-ups",
  "Planche leans",
  "Muscle-ups",
  "Pull-ups (wide grip)",
  "Pull-ups (close grip)",
  "Chin-ups (palms facing towards you)",
  "L-sit pull-ups",
  "Commando pull-ups",
  "Archer pull-ups",
  "Typewriter pull-ups",
  "Clapping pull-ups",
  "Towel pull-ups",
  "Hanging leg raises",
  "Windshield wipers",
  "Dragon flags",
  "Front lever raises",
  "One-arm hanging towel rows",
];

export default UpperBodyHardExercises;
